---
apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: jaeger
  labels:
    app: app1
spec:
  ports:
  - name: grpc
    port: 20051
  selector:
    app: app1 # it is a crd of DediServer. Pod has this label 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: jaeger
  labels:
    app: app1
spec:
  revisionHistoryLimit: 0 #NOTE: argocd
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: rival0605/jaeger:app1
        imagePullPolicy: Always
        command: ["/main"]
        args: ["-port=20051", "-endpointApp2=app2:20052","-endpointApp3=app3:20053",]
        env:
        - name: JAEGER_SERVICE_NAME
          value: app1
        - name: JAEGER_AGENT_HOST
          value: simplest-agent  # simplest-agent # 사이드카 패턴이라면 localhost로 하고 agent를 추가한다. 
        - name: JAEGER_AGENT_PORT
          value: "6831"

# https://medium.com/@masroor.hasan/tracing-infrastructure-with-jaeger-on-kubernetes-6800132a677
